# Site Settings
encoding: UTF-8
lang: en
permalink: /blog/:year/:month/:day/:title/
future: true

markdown: kramdown
kramdown:
  highlighter: rouge
  auto_id_prefix: ''
  smart_quotes: [ "apos", "apos", "quot", "quot" ]
  toc_levels: 1..3
  syntax_highlighter_opts:
    block:
      line_numbers: true

sass:
  style: compressed

# Site Data
url: https://hgnulb.github.io
baseurl: /hgnulb
title: 走在修行的大街上
description: "博客园"
keywords: 'software,engineer,testing,full-stack,blog,软件,工程师,测试,全栈,博客'
author:
  name: HGNULB
  job_title: Java 后端开发工程师
  profile: A blog that you won't read
  email: hgnulb@163.com
  social_links:
    - name: github
      url: https://github.com/hgnulb/
    - name: stackoverflow
      url: https://stackoverflow.com/users/10383025/
    - name: nowcoder
      url: https://www.nowcoder.com/profile/8667211/
    - name: leetcode
      url: https://leetcode-cn.com/u/hgnulb/

blog:
  cc_license: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
  cc_license_content: CC BY-NC-SA

paths:
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
  gh-pages: //cdn.jsdelivr.net/gh/hgnulb/hgnulb@gh-pages

busuanzi:
  enable: true

  site_uv: true
  site_uv_header: 本站总访客数
  site_uv_footer: 人

  site_pv: true
  site_pv_header: 本站总访问量
  site_pv_footer: 次

  page_pv: true
  page_pv_header: 本文总阅读量
  page_pv_footer: 次

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag